name: Build packages
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      INSPIRCD_DEB_PLATFORMS: ${{ matrix.package == 'deb' && matrix.platform || null }}
      INSPIRCD_RPM_PLATFORMS: ${{ matrix.package == 'rpm' && matrix.platform || null }}
      INSPIRCD_IGNORE_WARNINGS: 1
      INSPIRCD_PACKAGES: ${{ matrix.package }} html
      INSPIRCD_REVISION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve latest release
        run: |
          echo INSPIRCD_VERSION=$(curl https://api.github.com/repos/inspircd/inspircd/releases | jq --raw-output 'map(select((.draft | not) and (.tag_name | startswith("v4.")))) | first .tag_name | .[1:]') >> $GITHUB_ENV
      - name: Build packages
        run: ./build.sh
      - name: List packages
        run: cat ./build/packages.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: deb
            platform: debian-12
          - package: deb
            platform: debian-13
          - package: deb
            platform: ubuntu-20-04
          - package: deb
            platform: ubuntu-22-04
          - package: rpm
            platform: rocky-8
          - package: rpm
            platform: rocky-9
